export const spacing = {
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  xxxxl: 40,
  giant: 48,

  screenX: 20,
  screenY: 20,
  screenXCompact: 14,
  screenYCompact: 14,
  section: 24,
  sectionCompact: 16,
  sectionLg: 32,
  sectionLgCompact: 24,
  stackXs: 6,
  stackSm: 10,
  stackMd: 14,
  stackLg: 18,
  stackXl: 24,
  cardPadding: 20,
  cardPaddingCompact: 14,
  cardPaddingDense: 12,
  cardPaddingLg: 24,
  inputPaddingY: 16,
  inputPaddingX: 16,
  inputPaddingYCompact: 14,
  inputPaddingXCompact: 14,
  buttonPaddingY: 16,
  buttonPaddingX: 18,
  buttonPaddingYCompact: 14,
  buttonPaddingXCompact: 16,

  // Backward-compatible aliases
  SectionGap: 32,
  ElementGap: 16,
  ScreenPadding: 24,
};
