-- Patient-owned wig request drafts, exact-three virtual try-on choices, and
-- atomic final selection. Existing request-code triggers are intentionally
-- preserved because historical environments may still use either trigger.

create table if not exists public."Wig_Request_TryOn_Selections" (
  "Selection_ID" bigint generated by default as identity primary key,
  "Req_ID" integer not null references public."Wig_Requests"("Req_ID") on delete cascade,
  "Wig_ID" integer not null references public."Wigs"("Wig_ID") on delete restrict,
  "Wig_Specification_ID" integer not null references public."Wig_Specifications"("Wig_Specification_ID") on delete restrict,
  "Filter_ID" integer not null references public."Wig_AI_Filters"("Filter_ID") on delete restrict,
  "Selection_Order" smallint not null,
  "TryOn_Result_ID" integer references public."Wig_Virtual_TryOn_Results"("TryOn_Result_ID") on delete set null,
  "AI_Rank" smallint,
  "AI_Score" numeric(6, 3),
  "AI_Reason" text,
  "Is_AI_Best_Match" boolean not null default false,
  "Is_Final_Selection" boolean not null default false,
  "Created_At" timestamp with time zone not null default now(),
  "Updated_At" timestamp with time zone not null default now(),
  constraint wig_request_tryon_selection_order_check check ("Selection_Order" between 1 and 3),
  constraint wig_request_tryon_rank_check check ("AI_Rank" is null or "AI_Rank" between 1 and 3),
  constraint wig_request_tryon_score_check check ("AI_Score" is null or "AI_Score" between 0 and 100),
  constraint wig_request_tryon_unique_wig unique ("Req_ID", "Wig_ID"),
  constraint wig_request_tryon_unique_order unique ("Req_ID", "Selection_Order"),
  constraint wig_request_tryon_unique_result unique ("TryOn_Result_ID")
);

create unique index if not exists wig_request_tryon_one_final_per_request
on public."Wig_Request_TryOn_Selections" ("Req_ID")
where "Is_Final_Selection";

create unique index if not exists wig_request_tryon_one_rank_per_request
on public."Wig_Request_TryOn_Selections" ("Req_ID", "AI_Rank")
where "AI_Rank" is not null;

alter table public."Wig_Virtual_TryOn_Results"
  add column if not exists "Generated_Image_Path" text,
  add column if not exists "Generated_Image_URL" text;

comment on column public."Wig_Virtual_TryOn_Results"."Captured_Image_Path"
  is 'Patient source image path used for this try-on.';
comment on column public."Wig_Virtual_TryOn_Results"."Captured_Image_URL"
  is 'Patient source image URL used for this try-on.';
comment on column public."Wig_Virtual_TryOn_Results"."Generated_Image_Path"
  is 'Generated virtual try-on output path.';
comment on column public."Wig_Virtual_TryOn_Results"."Generated_Image_URL"
  is 'Generated virtual try-on output URL.';

alter table public."Wig_Request_TryOn_Selections" enable row level security;
alter table public."Wig_Virtual_TryOn_Results" enable row level security;
alter table public.wig_release_receipts enable row level security;
alter table public.wig_release_appeals enable row level security;

grant select on public."Wig_Request_TryOn_Selections" to authenticated;
grant select on public."Wig_Virtual_TryOn_Results" to authenticated;
grant select on public.wig_release_receipts to authenticated;
grant select on public.wig_release_appeals to authenticated;

-- New requests are created only through the authenticated RPC so ownership,
-- hospital, and staff-controlled fields cannot be spoofed by a mobile payload.
revoke insert on public."Wig_Requests" from authenticated;

create or replace function public.guard_patient_wig_safety_review_fields()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if auth.uid() is null or public.current_app_user_is_staff() then return new; end if;
  if tg_op = 'INSERT' then
    if new.review_status <> 'Pending' or new.reviewed_by is not null
       or new.reviewed_at is not null or new.review_notes is not null then
      raise exception 'Patients cannot set safety review fields';
    end if;
  elsif new.review_status is distinct from old.review_status
     or new.reviewed_by is distinct from old.reviewed_by
     or new.reviewed_at is distinct from old.reviewed_at
     or new.review_notes is distinct from old.review_notes then
    raise exception 'Patients cannot change safety review fields';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_guard_patient_wig_safety_review_fields
on public.patient_wig_safety_assessments;
create trigger trg_guard_patient_wig_safety_review_fields
before insert or update on public.patient_wig_safety_assessments
for each row execute function public.guard_patient_wig_safety_review_fields();

drop policy if exists "patients_read_own_tryon_selections" on public."Wig_Request_TryOn_Selections";
create policy "patients_read_own_tryon_selections"
on public."Wig_Request_TryOn_Selections" for select
using (
  public.current_app_user_is_staff()
  or exists (
    select 1 from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = "Wig_Request_TryOn_Selections"."Req_ID"
      and p."User_ID" = public.current_app_user_id()
  )
);

drop policy if exists "patients_read_own_virtual_tryons" on public."Wig_Virtual_TryOn_Results";
create policy "patients_read_own_virtual_tryons"
on public."Wig_Virtual_TryOn_Results" for select
using (
  public.current_app_user_is_staff()
  or exists (
    select 1 from public."Patients" p
    where p."Patient_ID" = "Wig_Virtual_TryOn_Results"."Patient_ID"
      and p."User_ID" = public.current_app_user_id()
  )
);

drop policy if exists "patients_read_own_wig_release_receipts" on public.wig_release_receipts;
create policy "patients_read_own_wig_release_receipts"
on public.wig_release_receipts for select
using (
  public.current_app_user_is_staff()
  or exists (
    select 1 from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = wig_release_receipts.req_id
      and p."User_ID" = public.current_app_user_id()
  )
);

drop policy if exists "patients_read_own_wig_release_appeals" on public.wig_release_appeals;
create policy "patients_read_own_wig_release_appeals"
on public.wig_release_appeals for select
using (
  public.current_app_user_is_staff()
  or exists (
    select 1 from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = wig_release_appeals.req_id
      and p."User_ID" = public.current_app_user_id()
  )
);

-- Catalog visibility is independent from stock. Availability is shown by the
-- client; unavailable catalog styles can still be selected as wish requests.
drop policy if exists "patients_read_available_wigs" on public."Wigs";
drop policy if exists "patients_read_wig_catalog" on public."Wigs";
create policy "patients_read_wig_catalog"
on public."Wigs" for select to authenticated
using (true);

drop policy if exists "patients_cancel_own_pending_wig_requests" on public."Wig_Requests";
create policy "patients_cancel_own_pending_wig_requests"
on public."Wig_Requests" for update
using (
  lower(trim(coalesce("Status", ''))) = 'pending'
  and "Request_Date" is not null
  and "Request_Date" >= now() - interval '7 days'
  and "Approved_By" is null
  and "Approved_At" is null
  and "Allocated_Wig_ID" is null
  and exists (
    select 1 from public."Patients" p
    where p."Patient_ID" = "Wig_Requests"."Patient_ID"
      and p."User_ID" = public.current_app_user_id()
  )
)
with check (
  lower(trim(coalesce("Status", ''))) = 'cancelled'
  and "Approved_By" is null
  and "Approved_At" is null
  and "Allocated_Wig_ID" is null
  and exists (
    select 1 from public."Patients" p
    where p."Patient_ID" = "Wig_Requests"."Patient_ID"
      and p."User_ID" = public.current_app_user_id()
  )
);

create or replace function public.patient_begin_or_resume_wig_request()
returns public."Wig_Requests"
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer := public.current_app_user_id();
  v_patient public."Patients"%rowtype;
  v_request public."Wig_Requests"%rowtype;
begin
  if auth.uid() is null or v_user_id is null then
    raise exception 'Authentication required';
  end if;

  perform pg_advisory_xact_lock(hashtext('patient-wig-request'), v_user_id);

  select * into v_patient
  from public."Patients"
  where "User_ID" = v_user_id
  order by "Patient_ID"
  limit 1;

  if v_patient."Patient_ID" is null then
    raise exception 'Patient record not found';
  end if;

  select * into v_request
  from public."Wig_Requests"
  where "Patient_ID" = v_patient."Patient_ID"
    and lower(trim(coalesce("Status", 'pending'))) not in
      ('released', 'rejected', 'cancelled', 'canceled', 'closed')
  order by "Updated_At" desc nulls last, "Req_ID" desc
  limit 1;

  if v_request."Req_ID" is not null then
    return v_request;
  end if;

  insert into public."Wig_Requests" (
    "Patient_ID", "Status", "Request_Date", "Requested_By", "Approved_By",
    "Approved_At", "Status_Reason", "Hospital_ID", "Requested_Wig_ID",
    "Allocated_Wig_ID", "Requested_Wig_Specification_ID", "Requested_Cap_Size",
    "Is_Wish_Request", "Fulfillment_Status", "Fulfillment_Bundle_ID"
  ) values (
    v_patient."Patient_ID", 'pending', now(), v_user_id, null,
    null, null, v_patient."Hospital_ID", null,
    null, null, null,
    false, 'catalog_review', null
  ) returning * into v_request;

  return v_request;
end;
$$;

create or replace function public.patient_set_wig_request_cap_size(
  p_req_id integer,
  p_cap_size text
)
returns public."Wig_Requests"
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public."Wig_Requests"%rowtype;
  v_cap text := trim(coalesce(p_cap_size, ''));
begin
  if v_cap = '' or not exists (
    select 1 from public."Wig_Specifications" ws
    where lower(ws."Cap_Size"::text) = lower(v_cap)
  ) then
    raise exception 'Select a valid catalog cap size';
  end if;

  select wr.* into v_request
  from public."Wig_Requests" wr
  join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
  where wr."Req_ID" = p_req_id
    and p."User_ID" = public.current_app_user_id()
    and lower(trim(coalesce(wr."Status", ''))) = 'pending'
    and wr."Requested_Wig_ID" is null
  for update of wr;

  if v_request."Req_ID" is null then
    raise exception 'This wig request cannot be changed';
  end if;
  if not exists (
    select 1 from public.patient_wig_safety_assessments a
    where a.req_id = p_req_id and a.information_confirmed = true
  ) then
    raise exception 'Complete the safety assessment before choosing a cap size';
  end if;

  update public."Wig_Requests"
  set "Requested_Cap_Size" = v_cap, "Updated_At" = now()
  where "Req_ID" = p_req_id
  returning * into v_request;
  return v_request;
end;
$$;

create or replace function public.patient_replace_wig_tryon_candidates(
  p_req_id integer,
  p_candidates jsonb
)
returns setof public."Wig_Request_TryOn_Selections"
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public."Wig_Requests"%rowtype;
begin
  if jsonb_typeof(p_candidates) <> 'array'
     or jsonb_array_length(p_candidates) <> 3
     or (select count(distinct (item->>'wig_id')::integer) from jsonb_array_elements(p_candidates) item) <> 3 then
    raise exception 'Select exactly three unique wigs';
  end if;

  select wr.* into v_request
  from public."Wig_Requests" wr
  join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
  where wr."Req_ID" = p_req_id
    and p."User_ID" = public.current_app_user_id()
    and lower(trim(coalesce(wr."Status", ''))) = 'pending'
    and wr."Requested_Wig_ID" is null
  for update of wr;

  if v_request."Req_ID" is null or coalesce(trim(v_request."Requested_Cap_Size"), '') = '' then
    raise exception 'Choose a cap size before selecting wigs';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_candidates) with ordinality c(item, position)
    left join public."Wig_AI_Filters" f
      on f."Filter_ID" = (c.item->>'filter_id')::integer
     and f."Wig_ID" = (c.item->>'wig_id')::integer
     and f."Is_Active" = true
    left join public."Wig_Specifications" ws
      on ws."Wig_Specification_ID" = (c.item->>'wig_specification_id')::integer
     and ws."Wig_ID" = (c.item->>'wig_id')::integer
    where f."Filter_ID" is null
       or ws."Wig_Specification_ID" is null
       or lower(ws."Cap_Size"::text) <> lower(v_request."Requested_Cap_Size")
  ) then
    raise exception 'Every selected wig must be an active catalog option matching the selected cap size';
  end if;

  delete from public."Wig_Virtual_TryOn_Results" r
  using public."Wig_Request_TryOn_Selections" s
  where s."Req_ID" = p_req_id and r."TryOn_Result_ID" = s."TryOn_Result_ID";
  delete from public."Wig_Request_TryOn_Selections" where "Req_ID" = p_req_id;

  insert into public."Wig_Request_TryOn_Selections" (
    "Req_ID", "Wig_ID", "Wig_Specification_ID", "Filter_ID", "Selection_Order"
  )
  select p_req_id,
         (c.item->>'wig_id')::integer,
         (c.item->>'wig_specification_id')::integer,
         (c.item->>'filter_id')::integer,
         c.position::smallint
  from jsonb_array_elements(p_candidates) with ordinality c(item, position);

  return query
  select * from public."Wig_Request_TryOn_Selections"
  where "Req_ID" = p_req_id
  order by "Selection_Order";
end;
$$;

create or replace function public.patient_record_wig_tryon_results(
  p_req_id integer,
  p_source_image_path text,
  p_source_image_url text,
  p_results jsonb
)
returns setof public."Wig_Request_TryOn_Selections"
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public."Wig_Requests"%rowtype;
  v_result record;
  v_tryon_id integer;
begin
  if jsonb_typeof(p_results) <> 'array'
     or jsonb_array_length(p_results) <> 3
     or (select count(distinct (item->>'wig_id')::integer) from jsonb_array_elements(p_results) item) <> 3
     or (select count(distinct (item->>'rank')::integer) from jsonb_array_elements(p_results) item) <> 3 then
    raise exception 'Exactly three uniquely ranked try-on results are required';
  end if;

  select wr.* into v_request
  from public."Wig_Requests" wr
  join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
  where wr."Req_ID" = p_req_id
    and p."User_ID" = public.current_app_user_id()
    and lower(trim(coalesce(wr."Status", ''))) = 'pending'
    and wr."Requested_Wig_ID" is null
  for update of wr;
  if v_request."Req_ID" is null then raise exception 'This wig request cannot be changed'; end if;

  if (select count(*) from public."Wig_Request_TryOn_Selections" where "Req_ID" = p_req_id) <> 3 then
    raise exception 'Confirm exactly three wigs before saving try-on results';
  end if;

  if exists (
    select 1 from jsonb_array_elements(p_results) item
    left join public."Wig_Request_TryOn_Selections" s
      on s."Req_ID" = p_req_id and s."Wig_ID" = (item->>'wig_id')::integer
    where s."Selection_ID" is null
       or (item->>'rank')::integer not between 1 and 3
       or coalesce(trim(item->>'generated_image_url'), '') = ''
  ) then
    raise exception 'Try-on results must match the three confirmed wigs';
  end if;

  delete from public."Wig_Virtual_TryOn_Results" r
  using public."Wig_Request_TryOn_Selections" s
  where s."Req_ID" = p_req_id and r."TryOn_Result_ID" = s."TryOn_Result_ID";

  update public."Wig_Request_TryOn_Selections"
  set "TryOn_Result_ID" = null, "AI_Rank" = null, "AI_Score" = null,
      "AI_Reason" = null, "Is_AI_Best_Match" = false,
      "Is_Final_Selection" = false, "Updated_At" = now()
  where "Req_ID" = p_req_id;

  for v_result in select item from jsonb_array_elements(p_results) item loop
    insert into public."Wig_Virtual_TryOn_Results" (
      "Patient_ID", "Req_ID", "User_ID", "Captured_Image_Path", "Captured_Image_URL",
      "Generated_Image_Path", "Generated_Image_URL", "Overlay_Settings", "Face_Detected",
      "Body_Detected", "Hair_Masking_Enabled", "Body_Occlusion_Enabled", "Filter_ID"
    )
    select v_request."Patient_ID", p_req_id, public.current_app_user_id(),
           coalesce(nullif(trim(p_source_image_path), ''), 'inline-patient-photo'),
           coalesce(nullif(trim(p_source_image_url), ''), 'inline-patient-photo'),
           nullif(trim(v_result.item->>'generated_image_path'), ''),
           trim(v_result.item->>'generated_image_url'),
           jsonb_build_object('provider', v_result.item->>'provider', 'rank', (v_result.item->>'rank')::integer),
           true, true, true, true, s."Filter_ID"
    from public."Wig_Request_TryOn_Selections" s
    where s."Req_ID" = p_req_id and s."Wig_ID" = (v_result.item->>'wig_id')::integer
    returning "TryOn_Result_ID" into v_tryon_id;

    update public."Wig_Request_TryOn_Selections"
    set "TryOn_Result_ID" = v_tryon_id,
        "AI_Rank" = (v_result.item->>'rank')::smallint,
        "AI_Score" = nullif(v_result.item->>'score', '')::numeric,
        "AI_Reason" = nullif(trim(v_result.item->>'reason'), ''),
        "Is_AI_Best_Match" = (v_result.item->>'rank')::integer = 1,
        "Updated_At" = now()
    where "Req_ID" = p_req_id and "Wig_ID" = (v_result.item->>'wig_id')::integer;
  end loop;

  return query select * from public."Wig_Request_TryOn_Selections"
  where "Req_ID" = p_req_id order by "AI_Rank";
end;
$$;

create or replace function public.patient_finalize_wig_request(
  p_req_id integer,
  p_wig_id integer,
  p_preview_url text,
  p_special_notes text default null
)
returns public."Wig_Requests"
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public."Wig_Requests"%rowtype;
  v_selection public."Wig_Request_TryOn_Selections"%rowtype;
  v_wig public."Wigs"%rowtype;
  v_spec public."Wig_Specifications"%rowtype;
  v_preview_url text;
begin
  select wr.* into v_request
  from public."Wig_Requests" wr
  join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
  where wr."Req_ID" = p_req_id
    and p."User_ID" = public.current_app_user_id()
    and lower(trim(coalesce(wr."Status", ''))) = 'pending'
    and wr."Requested_Wig_ID" is null
  for update of wr;
  if v_request."Req_ID" is null then raise exception 'This wig request cannot be submitted'; end if;
  if not exists (
    select 1 from public.patient_wig_safety_assessments a
    where a.req_id = p_req_id and a.information_confirmed = true
  ) then
    raise exception 'Complete the safety assessment before submitting';
  end if;

  select * into v_selection from public."Wig_Request_TryOn_Selections"
  where "Req_ID" = p_req_id and "Wig_ID" = p_wig_id and "TryOn_Result_ID" is not null;
  if v_selection."Selection_ID" is null then raise exception 'Choose one of the three generated try-on wigs'; end if;
  select r."Generated_Image_URL" into v_preview_url
  from public."Wig_Virtual_TryOn_Results" r
  where r."TryOn_Result_ID" = v_selection."TryOn_Result_ID" and r."Req_ID" = p_req_id;
  if coalesce(trim(v_preview_url), '') = '' then raise exception 'The selected try-on preview is unavailable'; end if;

  select * into v_wig from public."Wigs" where "Wig_ID" = p_wig_id;
  select * into v_spec from public."Wig_Specifications"
  where "Wig_Specification_ID" = v_selection."Wig_Specification_ID" and "Wig_ID" = p_wig_id;
  if v_wig."Wig_ID" is null or v_spec."Wig_Specification_ID" is null then
    raise exception 'The selected catalog wig is no longer available';
  end if;

  update public."Wig_Request_TryOn_Selections"
  set "Is_Final_Selection" = ("Wig_ID" = p_wig_id), "Updated_At" = now()
  where "Req_ID" = p_req_id;

  insert into public."Wig_Request_Specifications" (
    "Req_ID", "Preferred_Color", "Preferred_Length", "Hair_Texture", "Cap_Size",
    "Style_Preference", "Special_Notes", "AI_Wig_Preview_URL", "Updated_At"
  ) values (
    p_req_id, v_spec."Hair_Color", v_spec."Hair_Length"::text, v_spec."Hair_Texture",
    v_spec."Cap_Size"::text, v_spec."Style", nullif(trim(p_special_notes), ''),
    v_preview_url, now()
  )
  on conflict ("Req_ID") do update set
    "Preferred_Color" = excluded."Preferred_Color",
    "Preferred_Length" = excluded."Preferred_Length",
    "Hair_Texture" = excluded."Hair_Texture",
    "Cap_Size" = excluded."Cap_Size",
    "Style_Preference" = excluded."Style_Preference",
    "Special_Notes" = excluded."Special_Notes",
    "AI_Wig_Preview_URL" = excluded."AI_Wig_Preview_URL",
    "Updated_At" = now();

  update public."Wig_Requests"
  set "Requested_Wig_ID" = p_wig_id,
      "Requested_Wig_Specification_ID" = v_spec."Wig_Specification_ID",
      "Requested_Cap_Size" = v_spec."Cap_Size"::text,
      "Is_Wish_Request" = not (
        coalesce(v_wig."Stock_Count", 0) > 0
        and lower(replace(replace(replace(coalesce(v_wig."Wig_Status", ''), '-', ''), ' ', ''), '_', '')) = 'available'
      ),
      "Fulfillment_Status" = case
        when coalesce(v_wig."Stock_Count", 0) > 0
         and lower(replace(replace(replace(coalesce(v_wig."Wig_Status", ''), '-', ''), ' ', ''), '_', '')) = 'available'
        then 'catalog_review' else 'wish_catalog_review' end,
      "Updated_At" = now()
  where "Req_ID" = p_req_id
  returning * into v_request;
  return v_request;
end;
$$;

create or replace function public.patient_accept_wig_release_receipt(p_receipt_id bigint)
returns public.wig_release_receipts
language plpgsql
security definer
set search_path = public
as $$
declare v_receipt public.wig_release_receipts%rowtype;
begin
  update public.wig_release_receipts r
  set received_confirmed_at = now(), terms_accepted_at = now(),
      accepted_by = public.current_app_user_id(), updated_at = now()
  from public."Wig_Requests" wr
  join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
  where r.receipt_id = p_receipt_id and wr."Req_ID" = r.req_id
    and p."User_ID" = public.current_app_user_id()
    and r.received_confirmed_at is null and r.terms_accepted_at is null and r.accepted_by is null
  returning r.* into v_receipt;
  if v_receipt.receipt_id is null then raise exception 'This receipt cannot be accepted'; end if;
  return v_receipt;
end;
$$;

create or replace function public.patient_submit_wig_release_appeal(
  p_receipt_id bigint, p_reason text, p_description text, p_evidence_paths jsonb default '[]'::jsonb
)
returns public.wig_release_appeals
language plpgsql
security definer
set search_path = public
as $$
declare v_receipt public.wig_release_receipts%rowtype; v_appeal public.wig_release_appeals%rowtype;
begin
  select r.* into v_receipt from public.wig_release_receipts r
  join public."Wig_Requests" wr on wr."Req_ID" = r.req_id
  join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
  where r.receipt_id = p_receipt_id and p."User_ID" = public.current_app_user_id();
  if v_receipt.receipt_id is null or now() > v_receipt.appeal_deadline then
    raise exception 'The appeal deadline has passed or the receipt is unavailable';
  end if;
  if jsonb_typeof(coalesce(p_evidence_paths, '[]'::jsonb)) <> 'array' then
    raise exception 'Appeal evidence must be a list';
  end if;
  insert into public.wig_release_appeals (
    receipt_id, req_id, submitted_by, reason, description, evidence_paths,
    status, reviewed_by, reviewed_at, decision_note
  ) values (
    p_receipt_id, v_receipt.req_id, public.current_app_user_id(), trim(p_reason),
    trim(p_description), coalesce(p_evidence_paths, '[]'::jsonb),
    'Pending Staff Review', null, null, null
  ) returning * into v_appeal;
  return v_appeal;
end;
$$;

revoke all on function public.patient_begin_or_resume_wig_request() from public;
revoke all on function public.patient_set_wig_request_cap_size(integer, text) from public;
revoke all on function public.patient_replace_wig_tryon_candidates(integer, jsonb) from public;
revoke all on function public.patient_record_wig_tryon_results(integer, text, text, jsonb) from public;
revoke all on function public.patient_finalize_wig_request(integer, integer, text, text) from public;
revoke all on function public.patient_accept_wig_release_receipt(bigint) from public;
revoke all on function public.patient_submit_wig_release_appeal(bigint, text, text, jsonb) from public;

grant execute on function public.patient_begin_or_resume_wig_request() to authenticated;
grant execute on function public.patient_set_wig_request_cap_size(integer, text) to authenticated;
grant execute on function public.patient_replace_wig_tryon_candidates(integer, jsonb) to authenticated;
grant execute on function public.patient_record_wig_tryon_results(integer, text, text, jsonb) to authenticated;
grant execute on function public.patient_finalize_wig_request(integer, integer, text, text) to authenticated;
grant execute on function public.patient_accept_wig_release_receipt(bigint) to authenticated;
grant execute on function public.patient_submit_wig_release_appeal(bigint, text, text, jsonb) to authenticated;
