create table if not exists public."Hair_Analysis_Comparisons" (
  "Comparison_ID" bigint generated by default as identity primary key,
  "User_ID" integer not null references public.users(user_id) on delete cascade,
  "Previous_AI_Screening_ID" integer not null references public."AI_Screenings" ("AI_Screening_ID") on delete cascade,
  "Current_AI_Screening_ID" integer not null references public."AI_Screenings" ("AI_Screening_ID") on delete cascade,
  "Comparison_Type" text not null,
  "Comparison_Summary" text not null,
  "Comparison_Details" jsonb not null default '{}'::jsonb,
  "Model" text not null,
  "Generation_Status" text not null default 'pending',
  "Created_At" timestamptz not null default now(),
  constraint hair_analysis_comparisons_distinct_screenings
    check ("Previous_AI_Screening_ID" <> "Current_AI_Screening_ID"),
  constraint hair_analysis_comparisons_type_check
    check ("Comparison_Type" in (
      'improved_visible_findings',
      'similar',
      'new_visible_concerns',
      'mixed_changes',
      'insufficient_comparable_data'
    )),
  constraint hair_analysis_comparisons_generation_status_check
    check ("Generation_Status" in ('pending', 'completed', 'failed')),
  constraint hair_analysis_comparisons_unique_pair
    unique ("Previous_AI_Screening_ID", "Current_AI_Screening_ID")
);

create index if not exists idx_hair_analysis_comparisons_user_created
on public."Hair_Analysis_Comparisons" ("User_ID", "Created_At" desc);

alter table public."Hair_Analysis_Comparisons" enable row level security;

drop policy if exists "donors_read_own_hair_analysis_comparisons"
on public."Hair_Analysis_Comparisons";

create policy "donors_read_own_hair_analysis_comparisons"
on public."Hair_Analysis_Comparisons"
for select
to authenticated
using (
  "User_ID" = public.current_app_user_id()
  or public.current_app_user_is_staff()
);

comment on table public."Hair_Analysis_Comparisons"
is 'Caches one nonmedical Gemini progress summary for an exact previous/current completed Hair Analysis pair.';

comment on column public."Hair_Analysis_Comparisons"."Comparison_Details"
is 'Structured visible-change details only; no donor photos, facial embeddings, biometric templates, or identity vectors are stored.';
